### ISSUE TITLE
Overwrite existing favicon

### ISSUE THREAD

**Issue by dannypernik** [Elliot67/env-specific-favicon#1]
Hi, just found your extension and really appreciate it! I was wondering if you'd be willing to add an option to overwrite an existing favicon with a custom image. I'd want to be able to select a custom image per url. This would allow differentiation and beautification of my tabs. Thank you for your consideration!

**Comment by Elliot67** [comment]
Hi @dannypernik ,

Great idea! I just added this feature in the latest update! You can now either customize the webpage favicon or replace it with an image in each rule.
Note that the image needs to be hosted online (accessible via a web URL) or you can paste a data URI (`data:.....`), you can easily find tools to make the conversion like [this one](https://www.base64-image.de/).

Your browser should auto update the extension in the coming hours/days.

**Comment by dannypernik** [comment]
Hooray! I love it so much. I particularly love that the icon updates within the extension options immediately after adding the URL. Excellent work. Out of curiosity, do you still have the option to change the name of the extension in Chrome? I think there's an opportunity to indicate broader applicability. Maybe "custom favicon selector"?

**Comment by Elliot67** [comment]
@dannypernik 
Yes, I think I can still change the name.
I have been thinking about doing that for a while but wasn't able to come up with a more suitable name. I wanted to emphasize my usage which is to get different favicon colors per website environments (dev/staging/production/...) but it would probably be better to use broader terms.

Since English isn't my first language, it's kinda hard for me to find the right words that will speak to most. Do you have any other suggestions?
- Custom favicon selector
- Favicon customizer
- ...

**Comment by dannypernik** [comment]
I like Favicon customizer. My first thought was that some people would think that the extension generated a favicon for their own website, but I don't think so actually. It's strong word choice that gets to the heart of the extension's function. The extension description makes it obvious too, and other use cases could be added there. The first line could say "Change the favicon for any site or URL substring." Anyone who is looking for this functionality would definitely be attracted by that name.

The only extension I see that uses "Favicon customizer" is Gmail favicon customizer, which does the same thing but for only 1 site. Weak :) 
https://chrome.google.com/webstore/detail/gmail-favicon-customizer/hbnnphjhkbdeagbpjcnihdgianfhdgoo

For what it's worth, I'm currently using your extension to distinguish between two Google spreadsheets that I keep pinned.

**Comment by dannypernik** [comment]
@Elliot67 your favicons just got cooler without you doing a thing! Google Sheets apparently made their favicon's cross transparent :)

![image](https://github.com/Elliot67/env-specific-favicon/assets/3347095/4e86dec0-ff1f-49b7-8fbb-3ad9288d6bdb)

**Comment by Elliot67** [comment]
Hey @dannypernik , I'm glad you like all the features !

Regarding the renaming,  I've recently been thinking about "Distinct Favicon", do you think it would be more suitable ? Do you have any others suggestions in that direction ? The real goal is just to find which words people would look for on Google for this specific task/issue.

**Comment by dannypernik** [comment]
@Elliot67 I think "distinct" works, but "custom" or "customize" is more likely to be searched IMO.
