### ISSUE TITLE
Not working for slack

### ISSUE THREAD

**Issue by wapiflapi** [Elliot67/env-specific-favicon#2]
Hey ! 

This is a cool extension ! Exactly what I'm looking for.

But I can't seem to get it working with Slack.

I'm not sure how slack works, but I'm suspect it's modifying it's favicon quite often (depending on if there are unread messages, etc.) Maybe that's interfering with what the extension is doing ?

I tried putting `.*` as a pattern for "Title", this shows me the extension works on most websites. But not Slack.

My goal is to be able to quickly differentiate different Slack tabs.

**Comment by Elliot67** [comment]
Hey @wapiflapi ,

Thanks for the report, I can reproduce it on Slack as well. I will try to take a look at it and deploy a fix in the next version if possible.

**Comment by wapiflapi** [comment]
Awesome! Thank you so much.

**Comment by Elliot67** [comment]
Hey @wapiflapi ,

It's been a long time but I was finally able to make a new release.
I had to change a lot of things, but the extension now supports website which dynamically updates the favicon.

I didn't push the release to the chrome store yet. I really doubt anything will break, but I'd like to test it in my everyday work for the following week before releasing it to everyone.

However, if you'd like to use the new update, you can do so with the following steps:
- From the current extension option page(1.2), export the configuration
- Download the zip from the [latest release (1.3.0)](https://github.com/Elliot67/env-specific-favicon/releases)
- Unpack the zip archive
- Navigate to `chrome://extensions`
- Disable the current extension
- Check `developer mode` in the top right corner
- Click “Load Unpacked Extension”
- Select the folder
- From the option page (1.3), import your configuration

Once the new version is released in the chrome web store, you will just have to: 
- export your configuration (from 1.3)
- In `chrome://extensions`, delete the 1.3 version
- Enable the disabled extension (1.2)
- Import your configuration

**Comment by wapiflapi** [comment]
It's incredible that you made this happen! Thank you for working on it :-) I'll be looking forward to testing it once it reaches the store.

**Comment by Elliot67** [comment]
@wapiflapi The new version is available in the store, to force the update you just have to :
- Go to `chrome://extensions`
- Check `developer mode` in the top right corner
- Click the `update` button in the top left corner
